const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');
const root=path.resolve(__dirname,'..'),modules=new Map();
const cms=[{title:'Тусгай сургалт',summary:'Шинэ тайлбар',body:'<p>Нийтийн тайлбар</p>',i18n:{en:{title:'Hand-written course'}}}];
const repo={listCmsCached:async kind=>kind==='course'?cms:[],getSettingsCached:async()=>({teachers:[{name:'Нийтийн багш',info:'Багшийн танилцуулга'}],bank:{holder:'Нууц данс'}}),listPagesCached:async()=>[]};
function load(relative){const file=path.resolve(root,relative);if(modules.has(file))return modules.get(file).exports;const mod={exports:{}};modules.set(file,mod);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;const req=name=>{if(name==='next/cache')return {unstable_cache:fn=>fn};if(name==='./repo')return repo;if(name==='./journeys-db')return {listJourneysCached:async()=>[{name:'Аяллын нэр',transport:'Галт тэрэг'}]};if(name.startsWith('@/')||name.startsWith('.')){const base=name.startsWith('@/')?path.join(root,name.slice(2)):path.resolve(path.dirname(file),name);if(base.endsWith('.json'))return require(base);return load([base,base+'.ts',base+'.tsx'].find(f=>fs.existsSync(f)));}return require(name);};new Function('require','module','exports',code)(req,mod,mod.exports);return mod.exports;}
const {translateLiteral}=load('data/literal-translations.ts');const api=load('app/api/translations/route.ts');
const request=value=>new Request('https://example.com/api/translations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});
test('five-language labels round-trip from any previously selected language',()=>{for(const locale of ['mn','en','ko','ja','zh']){const result=translateLiteral('Аяллын зургууд',locale);assert.ok(result);if(locale!=='mn')assert.notEqual(result,'Аяллын зургууд');assert.equal(translateLiteral(result,'mn'),'Аяллын зургууд');}assert.equal(translateLiteral('  Аяллын   зургууд ','en'),'Journey photos');});
test('manual translations take precedence and only published text goes to the provider',async()=>{process.env.GOOGLE_TRANSLATE_API_KEY='test-only';let sent=[];global.fetch=async(url,opts)=>{assert.equal(url,'https://translation.googleapis.com/language/translate/v2');const body=JSON.parse(opts.body);sent.push(...body.q);return Response.json({data:{translations:body.q.map(q=>({translatedText:'Translated '+q}))}});};const r=await api.POST(request({locale:'en',sources:['Тусгай сургалт','Нийтийн тайлбар','Багшийн танилцуулга','Галт тэрэг','Нууц данс','Хэрэглэгчийн хувийн зурвас']}));const b=await r.json();assert.equal(b.translations['Тусгай сургалт'],'Hand-written course');assert.deepEqual(sent.sort(),['Нийтийн тайлбар','Багшийн танилцуулга','Галт тэрэг'].sort());assert.deepEqual(b.ignored,['Нууц данс','Хэрэглэгчийн хувийн зурвас']);});
test('missing provider is reported accurately while built-in labels still work',async()=>{delete process.env.GOOGLE_TRANSLATE_API_KEY;const b=await (await api.POST(request({locale:'ja',sources:['Аяллын зургууд','Шинэ тайлбар']}))).json();assert.equal(b.unavailable,true);assert.equal(b.translations['Аяллын зургууд'],'旅の写真');assert.equal(b.translations['Шинэ тайлбар'],undefined);assert.equal((await (await api.GET()).json()).configured,false);});
test('invalid locales, oversized requests and provider failures fail safely',async()=>{assert.equal((await api.POST(request({locale:'ru',sources:['Аяллын зургууд']}))).status,400);assert.equal((await api.POST(request({locale:'en',sources:Array(31).fill('Нэг')}))).status,400);assert.equal((await api.POST(request({locale:'en',sources:['А'.repeat(12001)]}))).status,413);process.env.GOOGLE_TRANSLATE_API_KEY='test-only';global.fetch=async()=>new Response('',{status:403});assert.equal((await api.POST(request({locale:'ko',sources:['Шинэ тайлбар']}))).status,503);delete process.env.GOOGLE_TRANSLATE_API_KEY;});
test('DOM translation preserves nodes, skipped form content and restores Mongolian',()=>{const node={nodeValue:'  Аяллын зургууд  ',parentElement:{closest:()=>null}},protectedNode={nodeValue:'Аяллын зургууд',parentElement:{closest:()=>({})}};global.NodeFilter={SHOW_TEXT:4};global.document={body:{querySelectorAll:()=>[]},createTreeWalker:()=>{let index=0;return{nextNode:()=>[node,protectedNode][index++]||null};}};global.MutationObserver=class{observe(){}disconnect(){}};global.requestAnimationFrame=()=>1;global.cancelAnimationFrame=()=>{};global.sessionStorage={getItem:()=>null,setItem(){}};global.window={setTimeout,clearTimeout};const {observeDocumentTranslation}=load('lib/document-translation.ts');for(const locale of ['en','ko','ja','zh','mn']){const stop=observeDocumentTranslation(locale);assert.equal(node.nodeValue,'  '+translateLiteral('Аяллын зургууд',locale)+'  ');assert.equal(protectedNode.nodeValue,'Аяллын зургууд');stop();}});
